[tool.pyright]
include = ["."]
exclude = [
    "**/__pycache__",
    "**/.terraform",
    "venv",
    ".tox",
]
typeCheckingMode = "strict"
strictParameterNoneValue = false
reportMissingParameterType = false

pythonVersion = "3.8"
pythonPlatform = "Linux"
